# Document:
# http://simiki.org/docs/configuration.html

url: https://Curtails.github.io/wiki/
title: Curtails's personal knowledge wiki
keywords: Technology, CTF, Network Security
description: A wiki website of Curtails when I learned new knowledgy.
author: Curtails

root: /wiki/

deploy:
    - type: git
      remote: origin
      branch: gh-pages
      
theme: simple